### ISSUE TITLE
Функция рандома тупит в большую сторону

### ISSUE THREAD

**Issue by evstigneew** [Ssid113/obs-script-delay-repeat-media#2]
![image](https://user-images.githubusercontent.com/26218365/110237852-516a5880-7f4f-11eb-9810-c17fefa63b61.png)
Погляди, казалось бы должно быть всегда не больше чем random to sec, но эпизодически фигачит больше.

**Comment by Ssid113** [comment]
Переработал функцию рандома. Теперь ведет себя так как и задумывалось.
[https://github.com/Ssid113/obs-script-delay-repeat-media/releases/tag/v0.2.1](url)
